// * IMPORTS * //

// * FUNCTIONS * //

const randomPersonGen = () => {
  // Genrate Random Names
  function generateRandomName(firstNames) {
    const randomFirstName =
      firstNames[Math.floor(Math.random() * firstNames.length)]
    return `${randomFirstName}`
  }

  // Generate Random Gender
  randomGender = () => {
    let gender = Math.floor(Math.random() * 2)
    if (gender === 0) {
      return 'male'
    } else {
      return 'female'
    }
  }

  // Give a random age from age 18-60
  randomAge = () => {
    let age = Math.floor(Math.random() * 50) + 18
    return age
  }

  // Gender equals the random gender
  const gender = randomGender()

  let names = []

  // Give names based on gender
  if (gender === 'male') {
    names = [
      'Aaron',
      'Adam',
      'Adrian',
      'Alan',
      'Albert',
      'Alex',
      'Alexander',
      'Alfred',
      'Andrew',
      'Anthony',
      'Arthur',
      'Austin',
      'Benjamin',
      'Bradley',
      'Brandon',
      'Brian',
      'Bruce',
      'Caleb',
      'Cameron',
      'Charles',
      'Christian',
      'Christopher',
      'Clifford',
      'Colin',
      'Connor',
      'Daniel',
      'David',
      'Dennis',
      'Derek',
      'Donald',
      'Douglas',
      'Dylan',
      'Edward',
      'Elijah',
      'Eric',
      'Ethan',
      'Evan',
      'Francis',
      'Frank',
      'Gabriel',
      'Gary',
      'George',
      'Gerald',
      'Gregory',
      'Harold',
      'Harry',
      'Henry',
      'Ian',
      'Isaac',
      'Jack',
      'Jacob',
      'James',
      'Jason',
      'Jeffrey',
      'Jeremy',
      'Jerry',
      'Jesse',
      'John',
      'Jonathan',
      'Jordan',
      'Joseph',
      'Joshua',
      'Justin',
      'Keith',
      'Kenneth',
      'Kevin',
      'Kyle',
      'Larry',
      'Lawrence',
      'Leo',
      'Liam',
      'Logan',
      'Louis',
      'Lucas',
      'Luke',
      'Mark',
      'Matthew',
      'Michael',
      'Nathan',
      'Nicholas',
      'Noah',
      'Oliver',
      'Oscar',
      'Patrick',
      'Paul',
      'Peter',
      'Philip',
      'Raymond',
      'Richard',
      'Robert',
      'Roger',
      'Ronald',
      'Ryan',
      'Samuel',
      'Scott',
      'Sean',
      'Stephen',
      'Steven',
      'Terry',
      'Thomas',
      'Timothy',
      'Todd',
      'Tyler',
      'Victor',
      'Vincent',
      'Walter',
      'Wayne',
      'William',
      'Wyatt',
      'Xavier',
      'Zachary',
    ]
  } else if (gender === 'female') {
    names = [
      'Abigail',
      'Alexandra',
      'Alice',
      'Amanda',
      'Amelia',
      'Amy',
      'Anna',
      'Ashley',
      'Ava',
      'Barbara',
      'Beatrice',
      'Beverly',
      'Brenda',
      'Brittany',
      'Camila',
      'Catherine',
      'Charlotte',
      'Chloe',
      'Christina',
      'Clara',
      'Claudia',
      'Crystal',
      'Daisy',
      'Danielle',
      'Deborah',
      'Diana',
      'Donna',
      'Dorothy',
      'Emily',
      'Emma',
      'Eva',
      'Faith',
      'Felicity',
      'Florence',
      'Gabriella',
      'Grace',
      'Hannah',
      'Harper',
      'Hazel',
      'Heather',
      'Isabella',
      'Jacqueline',
      'Jasmine',
      'Jennifer',
      'Jessica',
      'Jocelyn',
      'Joyce',
      'Julia',
      'Katherine',
      'Kayla',
      'Kimberly',
      'Lillian',
      'Linda',
      'Lucy',
      'Madison',
      'Megan',
      'Melissa',
      'Michelle',
      'Natalie',
      'Nicole',
      'Olivia',
      'Pamela',
      'Patricia',
      'Penelope',
      'Rachel',
      'Rebecca',
      'Rose',
      'Ruby',
      'Samantha',
      'Sarah',
      'Savannah',
      'Scarlett',
      'Sharon',
      'Sophia',
      'Stephanie',
      'Susan',
      'Taylor',
      'Vanessa',
      'Victoria',
      'Violet',
      'Virginia',
      'Wendy',
      'Whitney',
      'Willow',
      'Ximena',
      'Yvonne',
      'Zoe',
    ]
  }

  // Return the person
  return {
    name: generateRandomName(names),
    age: randomAge(),
    gender: gender,
  }
}

// * EXPORTS * //
module.exports = randomPersonGen
